[tool.briefcase]
project_name = "Different Strokes"
bundle = "com.tincrease"
version = "0.0.7"
url = "https://tincrease.com/differentstrokes"
license = "BSD license"
author = 'saluk'
author_email = "saluk64007@gmail.com"

[tool.briefcase.app.differentstrokes]
formal_name = "Different Strokes"
description = "pyweek 30 castaway game"
icon = "src/differentstrokes/resources/differentstrokes"
sources = ['src/differentstrokes']
requires = []


[tool.briefcase.app.differentstrokes.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.differentstrokes.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.differentstrokes.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.differentstrokes.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.differentstrokes.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
